spring.application.name=Ticketing-System

#Server Port
server.port= 7777

#DB config
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = mysql://${{MYSQLUSER}}:${{MYSQL_ROOT_PASSWORD}}@${{RAILWAY_TCP_PROXY_DOMAIN}}:${{RAILWAY_TCP_PROXY_PORT}}/${{MYSQL_DATABASE}}
spring.datasource.username = ${{MYSQLUSER}}
spring.datasource.password = ${{MYSQL_ROOT_PASSWORD}}

#jpa config
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
#new---------
spring.jpa.properties.hibernate.format_sql=true 


#Virtual Threads (The Java 25 Power Feature) #new-------
spring.threads.virtual.enabled=true

#Enable Optimistic Locking Logging #new---------
logging.level.org.hibernate.orm.jdbc.bind=TRACE
